apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matverseny-frontend
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/name: matverseny-frontend
spec:
  tls:
    - hosts:
        - matverseny.apps.okd4.home.zoltanszepesi.com
      secretName: matverseny-frontend-tls
  rules:
    - host: matverseny.apps.okd4.home.zoltanszepesi.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: matverseny-frontend
                port:
                  number: 80

