- op: replace
  path: /spec/tls/0/hosts/0
  value: admin.matverseny.apps.okd4.home.zoltanszepesi.com
- op: replace
  path: /spec/rules/0/host
  value: admin.matverseny.apps.okd4.home.zoltanszepesi.com

