apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matverseny-admin
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/name: matverseny-admin
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - HOSTNAME
      secretName: matverseny-admin-tls
  rules:
    - host: HOSTNAME
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: matverseny-admin
                port:
                  number: 80
