apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matverseny-backend

resources:
  - ../../../base/matverseny-backend

patches:
  - target:
      kind: Ingress
      name: matverseny-backend
    path: ingress-hostname-patch.yaml

