apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matverseny-backend

resources:
  - ../../../base/matverseny-frontend

patches:
  - target:
      kind: Ingress
      name: matverseny-frontend
    path: ingress-hostname-patch.yaml

