apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matverseny-backend

resources:
  - ../../../base/iam

patches:
  - target:
      kind: Ingress
      name: iam
    path: ingress-hostname-patch.yaml

